---
- name: Deploy WAR from S3
  hosts: webservers
  become: yes

  vars:
    local_war_path: "/tmp/{{ ARTIFACT_NAME }}"
    remote_tomcat_path: "/home/ec2-user/apache-tomcat/webapps/{{ ARTIFACT_NAME }}"

  tasks:
    - name: Download WAR file from S3 to localhost
      amazon.aws.s3_object:
        bucket: "{{ BUCKET_NAME }}"
        object: "{{ ARTIFACT_NAME }}"
        dest: "{{ local_war_path }}"
        mode: get
      delegate_to: localhost
      run_once: true

    - name: Copy WAR file from localhost to remote Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ local_war_path }}"
        dest: "{{ remote_tomcat_path }}"


