---
- name: Update web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Get Artifact from S3
      amazon.aws.s3_object:
        bucket: "{{ BUCKET_NAME }}"
        object: "{{ ARTIFACT_NAME }}"
        dest: "/tmp/{{ ARTIFACT_NAME }}"
        mode: get
      delegate_to: localhost

